# Panslopticon config

# Detection signals
[detect]
# Emojis that AI typically likes to use; regex
emojis = "👋|❤️|📫|🔥|🚀|📁|📂|✨|✅|📦|⚡|🔍|🤖|💥"

# Maximum README length in characters considered to be excessive
excessive_readme_length = 5000

# Maximum commit body length in characters
excessive_commit_length = 250

# Signals to potentially consider a README to be AI slop
readme_signals = [
    "(?i)load-bearing",
    "(?i)no .* no .* just .*",
    "(?i)it's not (just)?.* it's .*",
    "(?i)blazing.*fast",
    # "(?i)gpu-accelerated",
    # "(?i)web-?scale",
    "(Project|Repo.*) (?i)(overview|layout|structure)",
    "```mermaid",
    " · ", # centre dot unicode
    "(?i)no more .*\\.",
    "(?i)how it works",
    "(?i)(future work)|(suggested milestones)",
    "(?i)agent (skill|contract)",
    "(?i)bring-your-own",
    "(?i)early day.*(bug.*|feedback) welcome",
    "(?i)the point is",
    # https://claudisms.ai/
    "(?i)where it gets interesting",
    "(?i)((and )?that matters)|this matters",
    "(?i)lessons learned|lessons-learned",
    "(?i)the whole (ball)?-?game",
    "(?i)key takeaways",
    "(?i)delve",
    "(?i)a testament to"
]

# Regexes to detect AI coding tools in Git commits
[detect.commit]
claude = ["(?i)Claude.*(Code|Opus|Fable|Sonnet|Haiku)", "(?i)noreply@anthropic.com", "(?i)[0-9]+M context", "(?i)Claude-Session"]
copilot = ["(?i)Co-(authored|created|developed).*Copilot", "(?i)copilot@github.com", "175728472+Copilot"]
codex = ["(?i)OpenAI Codex", "(?i).*@openai.com"]
# these are from:
# https://codeberg.org/polyphony/repo-slopscore/src/branch/main/detection_tokens/tools.json
coderabbit = ["noreply@coderabbit.ai"]
gemini = ["(?i)gemini (pro|flash)", "(?i)antigravity"]

# NOTE: often the commits contain higher levels of slop
generic = [
    "(--)|→|×|–|—|⸺|⸻", # emdash/unicode
    "(?i)([0-9]+)?.*(tests )?(pass|passing)",
    "(?i)rebrand logo?",
    "(?i)belt-and-suspenders", # what the fuck does this even mean lmao; Claude-ism apparently
    "(?i)load-bearing",
    "(?i)no more .*\\.",
    # https://claudisms.ai/
    "(?i)harness"
]

# TODO grep in more MD files (locate all MD files in the repo and grep them against our)

# Regexes to detect particular AI coding tools in files
[detect.files]
claude = [".claude", "CLAUDE.md"]
cursor = [".cursor"]
copilot = [".github/skills"]
codex = [".codex", "CODEX.md"]
gemini = [".gemini"]
generic = ["AGENTS.md", "SKILLS.md", "AI_GUIDE.md", ".agents", ".agent"]

# Ingress locations
[ingress]
# GitHub tags to source slop from
gh_tags = [
    "ai", "mcp", "self-hosted", "selfhosted", "rust", "frontend", "crypto", "react", "api", "saas", "fastapi",
    "webapp", "fpga", "asic", "chip", "python", "javascript", "cpp", "gpu", "library", "c", "webgpu", "java",
    "kotlin", "flask", "zig", "compiler", "parser", "custom-language", "interpreter", "game", "unity",
    "unreal", "gamedev", "kernel", "neovim", "julia", "high-performance-computing", "hpc", "simulation", "llm",
    "big-data", "sql", "rag", "embedded", "rtos", "kernel", "verilog", "systemverilog", "risc-v", "typst",
    "linux", "android", "jupyter-notebook", "godot", "scala", "app", "agents", "nodejs", "lisp", "lua",
    "racket", "scheme", "ocaml", "clojure", "framework", "e-commerce", "blockchain", "canvas", "game-engine",
    "nlp", "quant", "browser", "hacktoberfest", "claude", "database", "vector", "code-quality",
    "code-analysis", "npm", "single-file", "nextjs", "offline", "zero-dependency", "css", "html",
    "cybersecurity", "exploit", "json", "yaml", "hack-tool", "hacker"
]

# Minimum stars even for slop; used as kind of a spam filter
gh_min_stars = 2

# repo must be created after this date to be considered slop
# currently this is 1 Jan 2025; technically Devin was released earlier but I think no one used it
# ! MUST BE RFC 2822 !
gh_date_cutoff = "Wed, 1 Jan 2025 00:00:00 +0000"

# Number of milliseconds to wait between GitHub HTTP HEAD requests
gh_http_head_wait_ms = 1000

# GitHub tags to NOT search for, when searching for ham
# These would all be slop most likely anyway
gh_ham_tags_blocklist = [
    "ai", "mcp", "crypto", "saas", "llm", "big-data", "agents", "rag", "blockchain", "claude"
]

# Number of rounds of a GitHub broad search (just "stars:>=gh_min_stairs") to do
gh_broad_search_num = 20

# Select a random page between 1 and this many pages in the broad search
gh_broad_search_pages_max = 10

# Score calculation
[scoring]
# Each AI commit gains this many points. That total score is then divided by the total number of commits in
# the repo (to normalise it)
ai_commit = 65.0
# this isn't really an incredibly good metric so we don't weight it very highly normalised per comment
excessively_long_commit = 5.0

readme_signal = 50.0
emoji = 15.0
emdash = 10.0
# factor multiply the README score by, this is indicative of the length of an "average" README
readme_multiplier = 2000.0

# A single AI file that is not hidden
ai_file = 50.0

# An AI file that **is** hidden, means the author intentionally is trying to hide it from us...
ai_file_hidden = 250.0

# This is high because it needs to weigh against the other scores, which are applied per commit
excessively_long_readme = 15.0

# !! The all important threshold to decide if a project is slop or not !!
threshold = 75

# Ham is considered to be less than or equal to this
ham_threshold = 40

# Storage dataset
[storage]
# Directory to store repos
dataset_path = "/mnt/ext/panslopticon"

# Keep downloaded repos?
download_repos = true
