# Panslopticon config

# Detection signals
[detect]

# Emojis that AI typically likes to use; regex
emojis = "👋|❤️|📫|🔥|🚀|📁|📂|✨|✅|📦|⚡|🔍|🤖|💥"

# Mean commits per day considered to be excessive
excessive_commits_thresh = 7

# Maximum README length in characters considered to be excessive
excessive_readme_length = 2000

# Maximum commit body length in characters
excessive_commit_length = 100

# Signals to potentially consider a README to be AI slop
readme_signals = [
    "(?i)load-bearing",
    "(?i)no .* no .* just .*",
    "(?i)it's not (just)?.* it's .*",
    "(?i)blazing.*fast",
    "(?i)gpu-accelerated",
    "(?i)web-?scale",
    "(Project|Repo.*) (?i)(overview|layout|structure)",
    "```mermaid",
    " · ", # centre dot
    "(?i)no more .*\\.",
    "(?i)how it works",
    "(?i)(future work)|(suggested milestones)",
    "(?i)agent (skill|contract)",
    "(?i)bring-your-own",
    "(?i)early day.*(bug.*|feedback) welcome"
]

# Regexes to detect AI coding tools in Git commits
[detect.commit]
claude = ["(?i)Claude (Code|Opus|Fable)", "(?i)noreply@anthropic.com", "(?i)[0-9]+M context", "(?i)Claude-Session"]
copilot = ["(?i)Co-(authored|created|developed).*Copilot", "(?i)copilot@github.com"]
codex = ["(?i)OpenAI Codex", "(?i).*@openai.com"]

generic = [
    "(--)|→|×|–|—|⸺|⸻", # emdash/unicode
    "(?i)([0-9]+)?.*(tests )?(pass|passing)",
    "(?i)rebrand logo?",
    "(?i)belt-and-suspenders", # what the fuck does this even mean lmao; Claude-ism apparently
    "(?i)load-bearing",
    "(?i)no more .*\\.",
]

# TODO: maybe look for this: (──)+.*(──)+

# TODO grep in more MD files (locate all MD files in the repo and grep them against our)

# Regexes to detect particular AI coding tools in files
[detect.files]
claude = [".claude"]
cursor = [".cursor"]
generic = ["AGENTS.md", "SKILLS.md", "AI_GUIDE.md", ".agents", ".agent"]

# Ingress locations
[ingress]
# GitHub tags to source slop from
gh_tags = [
    "ai", "mcp", "self-hosted", "selfhosted", "rust", "frontend", "crypto", "react", "api", "saas", "fastapi",
    "webapp"
]
gh_min_stars = 1

subreddits = [
    "rust", "zig", "typescript", "programming", "selfhosted", "fpga"
]

# Score calculation
[scoring]
ai_commit = 10.0
readme_signal = 1.0
emoji = 1.0
emdash = 2.0
excessively_long_readme = 1.0
excessively_long_commit = 0.5
