# Panslopticon config

# Detection signals
[detect]

# Emojis that AI typically likes to use; regex
emojis = "👋|❤️|📫|🔥|🚀|📁|📂|✨|✅|📦|⚡|🔍|🤖|💥"

# Mean commits per day considered to be excessive
excessive_commits = 7

# Maximum README length in characters considered to be excessive
excessive_readme_length = 2000

# Maximum number of emojis allowed in the README
excessive_emojis = 5

# Maximum number of emdashes allowed in the README
emdash_limit = 5

# Maximum commit body length in characters
excessive_commit_length = 100

# Signals to potentially consider a README to be AI slop
readme_signals = [
    "(?i)load-bearing",
    "(?i)no .* no .* just .*",
    "(?i)it's not (just)?.* it's .*",
    "(?i)blazing.*fast",
    "(?i)gpu-accelerated",
    "(?i)web-?scale",
    "(Project|Repo.*) (?i)(overview|layout|structure)",
    "```mermaid",
    " · ", # centre dot
    "(?i)no more .*\\.",
    "(?i)how it works",
    "(?i)(future work)|(suggested milestones)"
]

# Regexes to detect AI coding tools in Git commits
[detect.commit]
claude = ["(?i)Claude (Code|Opus|Fable)", "(?i)noreply@anthropic.com", "(?i)[0-9]+M context", "(?i)Claude-Session"]
copilot = ["(?i)Co-(authored|created|developed).*Copilot", "(?i)copilot@github.com"]
codex = ["(?i)OpenAI Codex", "(?i).*@openai.com"]

generic = [
    "(--)|→|×|–|—|⸺|⸻", # emdash/unicode
    "(?i)([0-9]+)?.*(tests )?(pass|passing)",
    "(?i)rebrand logo?",
    "(?i)belt-and-suspenders", # what the fuck does this even mean lmao; Claude-ism apparently
    "(?i)load-bearing",
    "(?i)no more .*\\.",
]

# TODO: maybe look for this: (──)+.*(──)+

# TODO grep in more MD files

# Regexes to detect particular AI coding tools in files
[detect.files]
claude = [".claude"]
cursor = [".cursor"]
generic = ["AGENTS.md", "SKILLS.md", "AI_GUIDE.md", ".agents", ".agent"]

# Ingress locations
[ingress]
# GitHub tags to source slop from
gh_tags = [
    "ai", "mcp", "self-hosted", "selfhosted", "rust", "frontend", "crypto", "react", "api", "saas", "fastapi"
]

subreddits = [
    "rust", "zig", "typescript", "programming", "selfhosted", "fpga"
]

# Reddit post body/title signals
reddit_signals = [
    "(?i)no .* no .* just .*",
    "(?i)it's not just .* it's .*",
    "(?i)blazing.*fast",
    "(?i)web-?scale",
    "(?i)solo (builder|creator|engineer|dev|developer|hacker)",
    "(?i)gpu-accelerated",
    "(?i)no more .*",
    "(?i)(i|i'm) (built|building|created) .*((a|an).*|—)",
    "(?i)no .*,.*,.*\\.", # e.g. "No cloud, 100% free, single binary."; maybe a bit broad
]
